### ISSUE TITLE
特技修改-勇将

### ISSUE THREAD

**Issue by chuckeytang** [duanrui71/SanGame#10]
-入场获得【勇将】军策卡
-对武力低于{SelfStrength}的武将战法必暴击
【勇将】:全军战法气力充满，遇敌时释放战法(乱射,奋迅,突破)，战法威力提升，幅度由{CommanderName}武力决定

**Comment by duanrui71** [comment]
额外增加了勇将卡 ID ： 10012，需要增加配置  和 图标
增加了新的计略ID  RUSE_TYPE_YONGJIANG  10012
客户端 ：特效可能需要修正
策划：需要比对 ARG
