### ISSUE TITLE
特技修改-强行

### ISSUE THREAD

**Issue by chuckeytang** [duanrui71/SanGame#11]
-入场时附带【冲锋】效果并直冲敌阵
-【冲锋】过程中不受【混乱】【伪报】效果影响
-【冲锋】首次攻击时可同时攻击周围敌军
【冲锋】:军队疾驰前进,且首次普攻产生2倍伤害,{CommanderName}每星级可额外追加0.3倍伤害

**Comment by duanrui71** [comment]
策划 ： 此效果已经废弃 -【冲锋】过程中不受【混乱】【伪报】效果影响 
策划 ： 需要对比 Arg文件 。
客户端：检查是否需要新效果。
