### ISSUE TITLE
特技修改-虚实

### ISSUE THREAD

**Issue by chuckeytang** [duanrui71/SanGame#9]
-在场时敌军释放军策时,在敌阵周围派出【伏兵】
-在场时敌军派出武将时,在本阵周围派出【援军】
-首次派兵数为{AmbusherNum}个(每星级能多出1个伏兵/援军)
-派兵数逐次递减，最少为2个
-援军\伏兵战力由武将属性决定

**Comment by duanrui71** [comment]
策划：需要比对 TalentArg
客户端：查看特效是否正确
